#ifndef _ERRORS_H_
#define _ERRORS_H_

// ecall return values to the App
enum ERROR
{
    NO_ERROR,
    ERR_INVALID_OP_CODE,
    ERR_INVALID_CHANNEL,
    ERR_NO_CHANNEL,
    ERR_INVALID_PARAMS,
    ERR_INVALID_USER,
    ERR_NOT_ENOUGH_BALANCE,
    ERR_ALREADY_EXIST_CHANNEL,
    ERR_INVALID_RECEIVER,
    ERR_NOT_ENOUGH_FEE,
    ERR_SGX_ERROR_UNEXPECTED,
    ERR_SEAL_FAILED,
    ERR_UNSEAL_FAILED,
    ERR_DECRYPT_FAILED,
    ERR_ENCRYPT_FAILED,
    ERR_NO_RECEIVER,
    ERR_RECEIVER_NOT_READY,
    ERR_ADDRESS_NOT_EXIST,
    ERR_SETTLE_NOT_READY,
    ERR_CANNOT_CHANGE_TO_LOWER_BLOCK,
    ERR_TOO_LOW_AMOUNT_TO_SETTLE,
    ERR_TOO_LOW_DEPOSIT,
    ERR_NO_AUTHORITY,
    ERR_NO_USER_ACCOUNT,
    ERR_VERIFY_SIG_FAILED
};

#define MAX_UNSIGNED_LONG_LONG 9223372036854775807

// get the error message for the error index
const char* error_to_msg(int err);

#endif  // _ERRORS_H_