#ifndef _ERRORS_H_
#define _ERRORS_H_

#include <string>
using std::string;

// ecall return values to the App
enum ERROR
{
    NO_ERROR,
    ERR_INVALID_OP_CODE,
    ERR_INVALID_PARAMS,
    ERR_NOT_ENOUGH_BALANCE,
    ERR_NOT_ENOUGH_FEE,
    ERR_SGX_ERROR_UNEXPECTED,
    ERR_SEAL_FAILED,
    ERR_UNSEAL_FAILED,
    ERR_DECRYPT_FAILED,
    ERR_ENCRYPT_FAILED,
    ERR_NO_RECEIVER,
    ERR_RECEIVER_NOT_READY,
    ERR_SETTLE_NOT_READY,
    ERR_CANNOT_CHANGE_TO_LOWER_BLOCK,
    ERR_TOO_LOW_SETTLE_FEE,
    ERR_TOO_LOW_DEPOSIT,
    ERR_NO_AUTHORITY,
    ERR_NO_USER_ACCOUNT,
    ERR_VERIFY_SIG_FAILED,
    ERR_NO_MANAGER_KEYID
};

#define MAX_UNSIGNED_LONG_LONG 9223372036854775807

// get the error message for the error index
string error_to_msg(int err);

#endif  // _ERRORS_H_